
name: Build docs
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          path: .
          username: ${{github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}/md-to-conf
          registry: docker.pkg.github.com
          tags: latest
